### ISSUE TITLE
Clusterrole removes required field

### ISSUE THREAD

**Issue by howardjohn** [itaysk/kubectl-neat#38] opened 2020-06-30 17:46 UTC
```
$ echo 'apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - patch' | kubectl neat | kubectl apply -f -
The ClusterRole "role" is invalid: rules[0].apiGroups: Required value: resource rules must supply at least one api group
```

Looks like we remove the `apiGroups: [""]` which leads to a rejection when applying

**Comment by itaysk** [comment] 2020-07-01 06:48
Hi @howardjohn thanks for reporting this! this is caused by `neatEmpty` which recursively deletes empty values. in the first pass it saw an empty string and removed it, and in the second pass it saw what now became an empty array and removed that. This feature was meant to clean up after previous code removed default values and left their parents empty. Perhaps it was wrong to treat empty string as unwanted values, so I do consider this a bug.
I am working on an overall for this plugin, upgrading some of the internal mechanics, so it this issue can wait a week or so, it would be fixed in the upcoming "v2" release.

**Closed** 2020-10-04 07:10 UTC
