### ISSUE TITLE
kubectl neat removing resource values

### ISSUE THREAD

**Issue by dmitriishaburov** [itaysk/kubectl-neat#81] opened 2022-05-02 13:24 UTC
Input:
```
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 1Gi
```

output after `| kubectl neat`:
```
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 50m
```

Maybe there's some default relation between requests and limits but would be nice to see them both usually

**Comment by itaysk** [comment] 2024-07-12 12:19
unable to reproduce so closing. if you have more details feel free to reopen

**Closed by itaysk** 2024-07-12 12:19 UTC
